<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Formulaire</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js' integrity='sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==' crossorigin='anonymous'></script>
</head>

<body>
    <div class="px-4 py-5 my-5 text-center">
        <h1 class="display-5 fw-bold">Form Hero</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
        </div>
    </div>
    <div class="container">
        <!-- Error -->
        <?php if (isset($error)) : ?>
            <div class="alert alert-danger" role="alert">
                <ul>
                    <li> <?= $error ?> </li>
                </ul>
            </div>
        <?php endif; ?>

        <!-- Success -->
        <?php if (isset($notif)) : ?>
            <div class="alert alert-success" role="alert">
                <ul>
                    <li> <?= $notif ?> </li>
                </ul>
            </div>
        <?php endif; ?>

        <form class="row g-3" action='index.php' method='post'>
            <div class="col-md-6">
                <label for="validationName" class="form-label">Name</label>
                <input name='name' type="text" class="form-control" id="validationName" placeholder="Otto" required>
            </div>
            <div class="col-md-6">
                <label for="validationEmail" class="form-label">Email</label>
                <div class="input-group">
                    <span class="input-group-text" id="inputGroupPrepend2">@</span>
                    <input name='email' type="text" class="form-control" id="validationEmail" aria-describedby="inputGroupPrepend2" required>
                </div>
            </div>
            <div class="col-md-6">
                <label for="validationDefault03" class="form-label">Password</label>
                <input name='password' type="password" class="form-control" id="validationDefault03" required>
            </div>
            <div class="col-md-6">
                <label for="validationDefault05" class="form-label">Birthdate</label>
                <input name='birthdate' type="date" class="form-control" id="validationDefault05">
            </div>

            <div class="col-12">
                <button class="btn btn-primary" type="submit">Submit form</button>
            </div>
        </form>
    </div>
    <!--
    Affichage des users s'ils existent-->
    <?php if (isset($users)) : ?>
        <div class="container">
            <div class="card" style="width: 18rem;">
                <ul class="list-group list-group-flush">
                    <?php foreach ($users as $user) : ?>
                        <li class="list-group-item"><?= $user['name'] ?></li>
                    <?php endforeach; ?>

                </ul>
            </div>
        </div>
    <?php endif; ?>

</body>

</html>