<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bon de commande Liste</title>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-alpha3/css/bootstrap.min.css'/>
    <link rel='stylesheet' href='https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap5.min.css'/>
    
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>
    <script type="text/javascript" src="//cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap5.min.js"></script>
</head>
<body class="container">
    <h1>Bon de commande Liste</h1>
    
    <table id="myTable" class="table table-striped">
        <thead>
            <tr>
                <th>Commande</th>
                <th>Date de la commande</th>
                <th>Date de livraison</th>
                <th>Statut</th>
            </tr>
        </thead>
        <tbody>
            <!--Commencer la boucle php avec le foreach ici -->
            <?php foreach($orders as $order): ?>
                <tr>
                    <td>
                        <a href="bdc.php?num_order=<?= $order['orderNumber'] ?>"><?= $order['orderNumber'] ?></a>
                    </td>
                    <td><?= $order['orderDate'] ?></td>
                    <td><?= $order['shippedDate'] ?></td>
                    <td><?= $order['status'] ?></td>
                </tr>
            <?php endforeach; ?>
            <!-- Terminer la boucle php avec le foreach ici -->
        </tbody>
    </table>
    
    <script>
        
        $(function () {
            $('#myTable').DataTable();
        });
    </script>
</body>
</html>